ilario-moreni/laravel-boolbnb-team-5

database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2023_03_22_152015_create_apartments_table.php
database/migrations/2023_03_22_153513_create_messages_table.php
database/migrations/2023_03_22_154950_create_views_table.php
database/migrations/2023_03_22_164231_create_services_table.php
database/migrations/2023_03_23_091038_add_foreign_key_to_apartments_table.php
database/migrations/2023_03_23_091135_add_foreign_key_to_views_table.php
database/migrations/2023_03_23_091157_add_foreign_key_to_messages_table.php
database/migrations/2023_03_23_092734_create_apartment_sponsorship_table.php
database/migrations/2023_03_23_092750_create_apartment_service_table.php

migration fixed

---

config/apartment_db.php
database/seeders/ApartmentSeeder.php

apartment_seeder_done

---

app/Http/Controllers/Admin/ApartmentController.php
app/Http/Requests/StoreApartmentRequest.php
app/Http/Requests/UpdateApartmentRequest.php

store e update requests done

---

app/Http/Controllers/Admin/ApartmentController.php
config/filesystems.php

Create store show crud 23 03 23

---

resources/scss/app.scss
resources/views/admin/apartments/index.blade.php
resources/views/layouts/admin.blade.php

completed_functions_and_style

---

app/Http/Controllers/Admin/ApartmentController.php

fixed store

---

app/Http/Controllers/Admin/ApartmentController.php
resources/views/admin/apartments/index.blade.php

Alert Create,Update, delete,db vuoto,access negato

---

app/Http/Controllers/Admin/ServiceController.php
app/Models/Service.php
config/service_db.php
database/seeders/ServiceSeeder.php
resources/views/admin/apartments/index.blade.php
resources/views/admin/services/index.blade.php
resources/views/layouts/admin.blade.php
routes/web.php

crud services done

---

resources/js/app.js
resources/views/admin/apartments/index.blade.php
resources/views/admin/partials/modals.blade.php

Modal error

---

app/Http/Controllers/Auth/RegisteredUserController.php
app/Models/User.php
composer.json
composer.lock
database/migrations/2023_03_24_105154_update_users_table.php
database/migrations/2023_03_24_110514_update_apartments_table.php
resources/views/auth/register.blade.php

fixing migration

---

app/Http/Controllers/Admin/MessageController.php
composer.json
composer.lock
database/seeders/MessageSeeder.php
resources/views/admin/apartments/index.blade.php
resources/views/admin/apartments/show.blade.php
resources/views/admin/messages/index.blade.php
routes/web.php

Crud messages 24 03 23

---

app/Http/Controllers/Admin/ApartmentController.php
app/Http/Requests/StoreApartmentRequest.php
app/Http/Requests/UpdateApartmentRequest.php
resources/views/admin/apartments/create.blade.php
resources/views/admin/apartments/edit.blade.php
resources/views/admin/apartments/show.blade.php
resources/views/layouts/admin.blade.php

Crud services

---

resources/scss/app.scss
resources/views/admin/apartments/edit.blade.php
resources/views/admin/apartments/index.blade.php
resources/views/layouts/admin.blade.php

fix_style_completed

---

app/Http/Controllers/Admin/ApartmentController.php
app/Http/Controllers/Admin/MessageController.php
resources/scss/app.scss
resources/scss/partials/index.scss
resources/views/admin/apartments/index.blade.php
resources/views/admin/messages/index.blade.php

Count mess 27 03 23

---

resources/views/admin/apartments/edit.blade.php
resources/views/admin/apartments/index.blade.php
resources/views/admin/apartments/show.blade.php

placeholder done

---

app/Http/Controllers/Admin/ApartmentController.php
app/Http/Requests/StoreApartmentRequest.php
app/Http/Requests/UpdateApartmentRequest.php
public/js/aptValidation.js
resources/scss/app.scss
resources/views/admin/apartments/create.blade.php
resources/views/admin/apartments/edit.blade.php
resources/views/admin/apartments/index.blade.php
resources/views/admin/apartments/show.blade.php
resources/views/admin/partials/modals.blade.php
resources/views/auth/login.blade.php
resources/views/auth/register.blade.php
resources/views/layouts/admin.blade.php
resources/views/layouts/app.blade.php

change language

---

resources/views/admin/apartments/show.blade.php

fixed show

---

app/Http/Controllers/Api/ApartmentController.php
config/cors.php
routes/api.php

apartment_controller_api_completed

---

app/Http/Controllers/Admin/ApartmentController.php
app/Http/Controllers/Api/ApartmentController.php
routes/api.php

added filter services

---

app/Http/Controllers/Api/MessageController.php
app/Http/Requests/StoreMessageRequest.php
app/Models/Message.php
database/migrations/2023_04_03_143557_update_messages_table.php
database/migrations/2023_04_03_153716_reupdate_messages_table.php
routes/api.php

Message controller branch

---

app/Http/Controllers/Api/ApartmentController.php

Fixed filter services

---

app/Http/Controllers/Admin/ApartmentController.php
app/Http/Controllers/Api/ApartmentController.php

Order by km

---

app/Http/Controllers/Admin/ApartmentController.php
app/Http/Controllers/Api/ApartmentController.php
routes/api.php

add route sponsor

---

app/Http/Requests/StoreMessageRequest.php
database/migrations/2023_04_06_195337_rereupdate_messages_table.php

modify validation storemessage (name: required)

---

package-lock.json
package.json
public/js/showMessage.js
resources/scss/partials/index.scss
resources/views/admin/messages/index.blade.php

carmellaaa

---

app/Http/Controllers/Api/ApartmentController.php

Modifica fatta da Sophia sulla api delle sponsor

---

resources/scss/app.scss
resources/views/admin/apartments/create.blade.php
resources/views/admin/apartments/edit.blade.php
resources/views/admin/apartments/index.blade.php
resources/views/admin/apartments/show.blade.php
resources/views/admin/partials/modals.blade.php
resources/views/admin/sponsorships/index.blade.php
resources/views/layouts/admin.blade.php
resources/views/layouts/app.blade.php

Modifiche grafiche e responsive fatte

Modifiche grafica back-office
